version: 2
jobs:
  build:
    # The primary container is an instance of the first list image listed. Your build commands run in this container.
    docker:
      - image: docker:17.12.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies (bash because I'm lazy)
          command: |
            apk add --no-cache \
              bash
      - run:
          name: Log into Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS 
      - run:
          name: Build Docker images
          command: |
            bash ./build.sh
    
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
              branches:
                only: 
                  - master
                  - release